language: crystal

jobs:
  include:
  - stage: test
    name: "Check format"
    before_script: make build
    script: make test

deploy:
- provider: script
  name: "Run webhook to import catalog"
  script: curl https://shardbox.org/webhook/import_catalog --user $WEBHOOK_AUTH_TOKEN
  on:
    branch: master
