---
name: CLI Applications
shards:
- github: caravel-tool/caravel
- github: erdnaxeli/castblock
  description: Automatically skip sponsor segments in YouTube videos playing on Chromecast
- github: caian-org/coin
  description: Command-line application that performs currency conversion via the
    [Fixer API](https://fixer.io)
- github: crystallabs/crystime
  description: Advanced time, calendar, schedule, and remind library for Crystal
- github: PercussiveElbow/docker-escape-tool
  description: Tool to test if you're in a Docker container and attempt simple breakouts
- github: askn/fikri
  description: Simple CLI To-Do App
- github: jhass/github_desktop_notifications
- github: cooperhammond/irs
  description: Downloads audio and metadata from Spotify in order to package an mp3
    with both
- github: straight-shoota/md2pdf
  description: Convert markdown files to PDF with flexible template and stylesheet
- github: ryanprior/meet
  description: Start a jitsi meeting quickly from the comfort of your command line
- github: noraj/miniss
  description: CLI app & library that displays a list of open sockets; it is a minimal alternative to ss or netstat
- github: tbrand/mssh
  description: Simple and powerful job executor on remote nodes
- github: snipline/snipcli
  description: Command-line tool for Snipline
- github: mjago/sonicri
- github: sferik/spellout
  description: A command-line tool that converts input into the International Radiotelephony
    Spelling Alphabet
- github: porras/tlcr
  description: Simple terminal-based client for TLDR
- github: geolessel/trello-cli
  description: It's Trello, but snappy
- github: mamantoha/zipstream
  description: A command line tool that allows you to easily share files and directories
    over the network
