---
name: Configuration
shards:
- github: gdotdesign/cr-dotenv
  description: Loads .env file
- github: drum445/dotenv
  description: Load .env files in crystal
- github: grottopress/envy
  description: Load environment variables from YAML
- github: philnash/envyable.cr
  description: A simple YAML to ENV config loader
- github: luckyframework/habitat
  description: Type safe configuration for your classes and modules
- github: icyleaf/poncho
  description: A .env parser/loader improved for performance
- github: maiha/toml-config.cr
  description: TOML::Config class for handy use of crystal-toml
- github: icyleaf/totem
  description: Load and parse a configuration in JSON, YAML, dotenv formats
- github: dscottboggs/xdg.cr
  description: Constants representing the XDG config locations or their standard defaults
     if not set
- github: tijn/xdg_base_directory
  description: A Crystal implementation of the XDG Base Directory specs
  mirrors:
  - gitlab: tijn/xdg_base_directory
- github: shmibs/xdg_basedir
  description: A simple, spec-compliant crystal interface to the XDG base directories
